POST http://localhost:20001/api/auth/register
Content-Type: application/json

{
  "email": "aaa@bbb.com",
  "password": "aaaaaa",
  "username": "vasya"
}

###

POST http://localhost:20001/api/auth/login
Content-Type: application/json

{
  "email": "aaa@bbb.com",
  "password": "aaaaaa"
}

###

GET  http://localhost:20001/api/auth/checktoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBiYmIuY29tIiwidXNlcm5hbWUiOiJ2YXN5YSIsImlhdCI6MTY3Nzc1MzUyNiwiZXhwIjoxNjc3NzYwNzI2fQ.0-09kJQErBWXsJHd3d5Eu7p3YC6K28XKR84q_p35ZxI


###

GET  http://localhost:20001/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBiYmIuY29tIiwidXNlcm5hbWUiOiJ2YXN5YSIsImlhdCI6MTY3Nzc1MzUyNiwiZXhwIjoxNjc3NzYwNzI2fQ.0-09kJQErBWXsJHd3d5Eu7p3YC6K28XKR84q_p35ZxI

###

GET http://localhost:20001/api/users/dasd1as11g1g5sdf1fdsa1fa1cxz1csa11HIDHSADNLKASDF145sad185sa1d

###
