version: '3.5'
services:
  rabbitmq:
      image: rabbitmq:3.11-management
      ports:
        - '5672:5672'
        - '10100:15672'
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: test
      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 5s
        retries: 5

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-notify
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: guitar-shop-notify
    ports:
      - 27020:27017
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-guitar-shop-notify
    ports:
      - 22006:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fakesmtp
    hostname: fakesmtp
    ports:
      - '5025:5025'
      - '10000:5080'
