POST http://localhost:20006/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDA3OGEwMWU1YjkyNjQyZTI3ZTUwYSIsImVtYWlsIjoiYWFhQGJiYi5jb20iLCJ1c2VybmFtZSI6InZhc3lhIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3ODMwMTg0NSwiZXhwIjoxNjc4MzA5MDQ1fQ._KGTFfn6T7OWr8XuK2SNBWQImnN5GwjCvP9I0SRfz98
Content-Type: application/json

{
  "creatorUserId": "640078a01e5b92642e27e50a",
  "productId": "00807ff4-6bb2-4bbf-8924-d8903272d14e",
  "advantages": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "disadvantages": "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "comment": "Хороший комментарий",
  "score": 3
}

###

GET http://localhost:20006/api/comments/ea524872-b16f-445d-ad07-19eb2327aa4a?page=1


###
