version: '3.5'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: "guitarshop_products"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  guitarshop.products:
    image: guitarshop.products
    container_name: guitarshop.products.service
    network_mode: 'host'
    depends_on:
      - postgres
    ports:
      - 20002:3333
    env_file:
      - ./environments/development.env


networks:
  postgres:
    driver: bridge

