POST http://localhost:20006/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDA3OGEwMWU1YjkyNjQyZTI3ZTUwYSIsImVtYWlsIjoiYWFhQGJiYi5jb20iLCJ1c2VybmFtZSI6InZhc3lhIiwiaWF0IjoxNjc4MTMyMjkzLCJleHAiOjE2NzgxMzk0OTN9.5ktXNBd-yjnsy0PYZdZNW1dUqTxokjwbi4mK_mG71Co
Content-Type: application/json

{
  "creatorUserId": "640078a01e5b92642e27e50a",
  "productId": "640b67fc-49f2-4253-9bf2-9d4844389c99",
  "advantages": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "disadvantages": "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "comment": "Хороший комментарий",
  "score": 2
}

###

GET http://localhost:20006/api/comments/ea524872-b16f-445d-ad07-19eb2327aa4a?page=1


###
