export const GuitarShopCommentConstantValueEnum = {
  ADVANTAGES_MIN_LENGTH: 50,
  ADVANTAGES_MAX_LENGTH: 100,
  DISADVANTAGES_MIN_LENGTH: 50,
  DISADVANTAGES_MAX_LENGTH: 100,
  COMMENT_MIN_LENGTH: 5,
  COMMENT_MAX_LENGTH: 1024,
  SCORE_MIN_VALUE: 1,
  SCORE_MAX_VALUE: 5,
} as const;
