export const GuitarShopProductCardConstantValueEnum = {
  TITLE_MIN_LENGTH: 10,
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 20,
  DESCRIPTION_MAX_LENGTH: 1024,
  ARTICLE_MIN_LENGTH: 5,
  ARTICLE_MAX_LENGTH: 40,
  PRICE_MIN_LENGTH: 100,
  PRICE_MAX_LENGTH: 1_000_000,
} as const;
